### ISSUE TITLE
read_dropdown is not filtering appropriately when the list is sufficiently long

### ISSUE THREAD

**Issue by Xatrekak** [abstra-app/hackerforms-lib#17]
Type - self hosted
Version - hackerforms 0.2.1
install - via PyPi
OS - Linux Pop!_OS
Browser - Chromium Version 101.0.4951.41 (Official Build) (64-bit)

The read_dropdown function does not correctly filter all of the values when the list is sufficiently long.
Correct behavior is observed when there are fewer than 68 elements to be filtered as seen below:
![unfiltered](https://user-images.githubusercontent.com/6622041/166119568-687a92ef-b6b6-46de-b8c5-4e8867bafcb3.png)
![filtered_correct](https://user-images.githubusercontent.com/6622041/166119578-48fea6ab-5f1e-4528-984f-c0ee2f944369.png)

Once the list has 68 or more elements in it the list does not filter completely:
![filtered_incorrect](https://user-images.githubusercontent.com/6622041/166119617-76ceff3f-3158-4c05-b7c8-c3e63105b19a.png)
  
=================================================
=
 
More elements remain unfiltered the longer the list. However the count of unfiltered elements does not increase linearly with the length of the search list as seen with this list of 200 elements:
Before:
![unfiltered_long](https://user-images.githubusercontent.com/6622041/166119736-f1faa09e-470d-4171-be3d-a69609130ea8.png)
After:
![filtered_very_incorrect](https://user-images.githubusercontent.com/6622041/166119833-268514ff-9d16-478e-a18e-66a19efe61eb.png)

=================================================
=

Correct behavior is once again observed if the filter string is pasted in completely and not typed out character by character as seen with the list of 1000 elements:
![unfiltered_long](https://user-images.githubusercontent.com/6622041/166119736-f1faa09e-470d-4171-be3d-a69609130ea8.png)
![filtered_correct_long](https://user-images.githubusercontent.com/6622041/166119744-8dc0fbeb-66fe-41f8-b901-dc2dba6d9603.png)

**Comment by bernardowerneck** [comment]
Hi @Xatrekak , thank you for showing us this issue, it is most likely located in the front end side of our tool. We could not replicate the problem, could you send us the code snippet you ran so we can see what may be causing it?

**Comment by Xatrekak** [comment]
@bernardowerneck 

```
import hackerforms as hf
import requests
import json

#retreving info from a fastapi server
commanders_list = requests.get(f"http://127.0.0.1:8000/commanderlist").json()
short_list = commanders_list[:99]

#pass the retreived list to hackerforms
commander = hf.read_dropdown("Please select your commander", short_list, False)
#strip whitespace for REST call
commander = commander.replace(" ", "%20")
#send user choice to fastapi server and set the results
contents = requests.get(f"http://127.0.0.1:8000/commanders/{commander}").json()

#display the data returned from the fastapi server to the user
hf.display(contents)

```

Here is the contest of "short_list"
```
['Odric, Master Tactician', 'Edric, Spymaster of Trest', 'Izoni, Thousand-Eyed', 'Lazav, Dimir Mastermind', 'Celestial Kirin', 'Snapdax, Apex of the Hunt', 'Kamahl, Pit Fighter', 'Hogaak, Arisen Necropolis', 'Jasmine Boreal', 'Shaile, Dean of Radiance // Embrose, Dean of Shadow', 'Beledros Witherbloom', 'Nin, the Pain Artist', 'Pia Nalaar', 'Miara, Thorn of the Glade', 'Atris, Oracle of Half-Truths', 'Laelia, the Blade Reforged', 'Gutmorn, Pactbound Servant', 'Alesha, Who Smiles at Death', 'Nissa, Vastwood Seer // Nissa, Sage Animist', 'Linvala, Shield of Sea Gate', 'Slivdrazi Monstrosity', 'Lady Zhurong, Warrior Queen', 'Eron the Relentless', 'Nikara, Lair Scavenger', 'Ghalta, Primal Hunger', 'Jolrael, Empress of Beasts', 'Kyler, Sigardian Emissary', 'Malfegor', 'Mangara, the Diplomat', 'Alena, Kessig Trapper', 'Danitha Capashen, Paragon', 'Satsuki, the Living Lore', 'Niv-Mizzet, the Firemind', 'Kess, Dissident Mage', 'Noyan Dar, Roil Shaper', 'Gavi, Nest Warden', 'Vendilion Clique', 'Jin-Gitaxias, Progress Tyrant', 'Heliod, Sun-Crowned', 'Rorix Bladewing', "Kroxa, Titan of Death's Hunger", 'Ith, High Arcanist', 'Silvos, Rogue Elemental', 'Anya, Merciless Angel', 'Greasefang, Okiba Boss', 'Rielle, the Everwise', 'Asmodeus the Archfiend', 'Jadar, Ghoulcaller of Nephalia', 'Mechtitan', 'Lonis, Cryptozoologist', 'Alhammarret, High Arbiter', 'Niv-Mizzet, the Firemind', "Shessra, Death's Whisper", 'Lavinia, Azorius Renegade', 'Livio, Oathsworn Sentinel', "Jace, Vryn's Prodigy // Jace, Telepath Unbound", 'Jarad, Golgari Lich Lord', 'Evra, Halcyon Witness', 'Vadrok, Apex of Thunder', 'Karador, Ghost Chieftain', 'Surrak Dragonclaw', "Saryth, the Viper's Fang", 'Isshin, Two Heavens as One', 'Prosper, Tome-Bound', 'Karador, Ghost Chieftain', 'Subira, Tulzidi Caravanner', 'Minsc, Beloved Ranger', 'Leinore, Autumn Sovereign', 'Marrow-Gnawer', 'Kothophed, Soul Hoarder', 'Brago, King Eternal', 'Daxos, Blessed by the Sun', 'Kelsien, the Plague', 'Arasta of the Endless Web', 'Ayesha Tanaka', 'Lazav, Dimir Mastermind', 'Queen Marchesa', 'Visara the Dreadful', 'Purphoros, Bronze-Blooded', 'Patron of the Moon', 'Ich-Tekik, Salvage Splicer', 'Keiga, the Tide Star', 'Nevinyrral, Urborg Tyrant', 'Mirri, Weatherlight Duelist', 'Garza Zol, Plague Queen', 'Thraximundar', "Drizzt Do'Urden", 'Kess, Dissident Mage', 'Anya, Merciless Angel', 'Dromoka, the Eternal', 'Velomachus Lorehold', 'Rakdos, Lord of Riots', 'Tanazir Quandrix', 'Syr Elenora, the Discerning', "Kroxa, Titan of Death's Hunger", "Yuriko, the Tiger's Shadow", 'Mr. Orfeo, the Boulder', 'Selvala, Heart of the Wilds', 'Linden, the Steadfast Queen']
```

**Comment by bernardowerneck** [comment]
Found out what the problem was, there were duplicate labels in the array and we weren't handling them correctly. We just shipped the solution and it is already in production

**Comment by Xatrekak** [comment]
@bernardowerneck 
I appreciate the quick fix on this. Though it seems like another bug has been introduced.
The field width on the read_dropdown no longer automatically adjust to the width of the text fields that it contains.

![bad_field_length](https://user-images.githubusercontent.com/6622041/166344797-1430c84f-db97-4e12-972c-3fb899a7ecac.png)

Would you like me to open a separate issue for the regression?

**Comment by bernardowerneck** [comment]
@Xatrekak no need for the separate issue! Just shipped a quick fix for this problem, thanks for letting us know! It should be back to the previous behaviour
