### ISSUE TITLE
Not possible to run in local ? 

### ISSUE THREAD

**Issue by Skorkmaz88** [abstra-app/hackerforms-lib#35]
Right now when examples launched  it is launching the hackerforms.com with session information, which redirects to new website, without launching the example interface

`python ./examples/quiz.py` 

---
**Expected behavior:**

 Open the example in browser,
 
 **Output:**

Browser navigates to : https://www.abstracloud.com/

---

Also is possible to run in local system ? I see that socket.py has commented localhost version.

**Comment by felipereyel** [comment]
@Skorkmaz88 we just updated our product brand and moved the domain. sorry about the inconvenience.

If you uninstall (`pip uninstall hackerforms`) and install again (`pip install hackerforms`) the issue will be fixed.

About running locally we are working on releasing an OSS version but currently its not available. When this becomes available we'll notify you.

Best regards.
